name: Sample

on:
  pull_request:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build
        run: docker compose build

      - name: start containers
        run: docker compose up -d

      - name: exec docker container exec date
        run: docker compose exec app date
